Fix build error CMake target `deviceManager`
Missing dependency.

```shell
$ make
Scanning dependencies of target deviceManager
[  8%] Building CXX object CMakeFiles/deviceManager.dir/deviceManager.cpp.o
/workspace/deviceManager.cpp:2:10: fatal error: spdlog/spdlog.h: No such file or directory
    2 | #include <spdlog/spdlog.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/deviceManager.dir/build.make:82: CMakeFiles/deviceManager.dir/deviceManager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:117: CMakeFiles/deviceManager.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```