Fix build error CMake target `deviceManager`
Missing include header.

```
/workspace/deviceManager.cpp: In member function 'virtual void deviceManager::InternalThreadEntry()':
/workspace/deviceManager.cpp:17:9: error: 'usleep' was not declared in this scope
   17 |         usleep(500000);
      |         ^~~~~~
```